### PR TITLE
Fixed README.md file with correct characters for minilogo

### PR DESCRIPTION
**Pull request by Yith1**
I noticed a mistake in the README.md file. The characters for the minilogo were listed incorrectly.

### CODE REVIEW

**Comment by ondrascz** [comment]
Thanks for noticing and fixing

**Comment by Yith1** [comment]
No problem! It's been a great tool. I've been flying with the fonts I've made with it for the last couple of days.

I did also like to suggest that the example.bat file was included in the zip file. I had to help a friend with that.

Maybe also an example file for inav?

**Comment by ondrascz** [comment]
I will review the release .zip content. More examples are in the pipeline. The inav support is also planned. At this moment it supports only inav6 logo. The values and units are at different places in inav font compared to BF. also the decimal numbers are handled differenly, so it will need some work. I also don't know if inav6 support will be sufficient and how many pilots are and will be still flying inav5...

**Comment by Yith1** [comment]
I'm on iNav 5 at the moment on my planes. I've had too much to do updating all my quads/vtxes etc..!

**Pull request merged**
